---
title: "Temporal_DE_analysis"
author: "Johannes Schöneich"
date: "`r Sys.Date()`"
output: html_document

---
```{r}
library(clusterProfiler)
library(circlize)
library(ComplexHeatmap)
library(DOSE)
library(enrichplot)
library(glue)
library(ggplot2)
library(openxlsx)
library(reshape2)
library(rstatix)
library(scales)
library(tidyverse)
library(viridis)
library(ggsci)


harddrive <- "H:/231248/NTFS_3.64TB"
source(file.path(harddrive,"helper_functions.R"))
source(file.path(harddrive,"DE_analysis/DE_helperfunctions.R"))

# Define output folders
analysis_folder <- "DE_analysis/DE_LRT_uninfected"

plots_folder <- file.path(harddrive,analysis_folder,"tempDE/plots")
charts_folder <- file.path(harddrive,analysis_folder,"tempDE/charts")
```

# Temporal DE analysis
```{r}
# Read in the results from DE analysis in a list, 
# each element a new DE comparison
results.list <- readRDS(file.path(harddrive,analysis_folder,
                                  "DE_results.list_timepoint.Rds"))

# Read in the countmatrix
countmatrix <- read.csv(file.path(harddrive,
  "RNA_seq/RNAseq_uninfected/",
  "countmatrix_raw_batchcorr_LRT_RNAseq_uninfected.csv"),
  row.names = 1,header = TRUE)

# Gene co-expression
genename <- "mafb"

mafb <- read.xlsx(
  file.path(harddrive,
            "DE_analysis/temporal_DE/mafb_mutantvscontrol.DEG.all_new.xlsx"))

mafb.up <- mafb %>% filter(log2FoldChange >= 1) %>% pull(gene_name)
mafb.down <- mafb %>% filter(log2FoldChange <= - 1) %>% pull(gene_name)

# write.csv(mafb.up,file = file.path(harddrive,
#                           "DE_analysis/temporal_DE/mafb_up.csv"))
# 
# write.csv(mafb.down,file = file.path(harddrive,
# #                           "DE_analysis/temporal_DE/mafb_down.csv"))
# 
# genenames_up <- unique(read.csv(file.path(harddrive,
#  "DE_analysis/temporal_DE/annotated_blimp_up.csv"))$uniprot_gn_symbol)
# 
# genenames_down <- unique(read.csv(file.path(harddrive,
#  "DE_analysis/temporal_DE/annotated_blimp_down.csv"))$uniprot_gn_symbol)


blimp.up <- unique(read.csv(
  file.path(harddrive,
            "DE_analysis/temporal_DE/",
            "annotated_blimp_up.csv"))$uniprot_gn_symbol)

blimp.down <- unique(read.csv(
  file.path(harddrive,
            "DE_analysis/temporal_DE/",
            "annotated_blimp_down.csv"))$uniprot_gn_symbol)

# plotnames
NAME <- "tempDE"

# For GO -----------------

# GO cutoff: The minimum number of genes a pattern must posses to be considered for further GO analysis
go.cutoff <- 30

# Which ontology: choose between all, biological process (bp), 
# molecular function (mf) and cellular component (cc).
ont <- "bp"

# P-adjust cutoff. Adjustment method is benjamini-hochberg (FDR)
p.cutoff <- 0.05

# The number of GO terms per cluster to compare
topN  <- 5

# Count cutoff. The low end filtering of counts
count.cutoff <- 10

# Heatmap coloring options
pos_color <- "#E41A1C" # The color to which the significant p-values converge
pos_color_low <- "#fff5f0"

neg_color <- "#377EB8"
```

```{r}
if (!dir.exists(plots_folder)){
  dir.create(plots_folder,recursive = TRUE)
  dir.create(charts_folder,recursive = TRUE)
}
```

```{r}
# we know that results.list contains all relevant values, but we only take the 
# intermediate steps for the comparisons 
#head(results.list)
#head(countmatrix)

degenesdf <- as.data.frame(rbind(results.list$d01_d05,
                               results.list$d05_d10,
                               results.list$d10_d25))

#define DE genes by having either logfc of > 1 or < -1 and padj < 0.05
genes_to_keep <- degenesdf[abs(degenesdf$log2FoldChange) > 1 & 
                             degenesdf$padj < 0.05,"symbol"]

#TODO: make it so we read in the coldata so we can get the number of rows for arguments 
#instead of manually defining

cm2 <- countmatrix[,grep("d05i",colnames(countmatrix),invert = TRUE)]

cm2 <- cm2[unique(genes_to_keep),]
cm2 <- cm2[which(rowSums(cm2)>=60),] # keep all genes with at least 60 counts

cm2.list <- list("cm2_d1" = cm2[,1:4],"cm2_d5" = cm2[,5:8],
                 "cm2_d10" = cm2[,9:11],"cm2_d25" = cm2[,12:14])

cm2.list <- lapply(cm2.list,function(x){x$mean <- rowMeans(x);return(x)})

means_raw <- as.data.frame(sapply(cm2.list,function(x){x$mean}))

colnames(means_raw) <- c("mean_d1_raw","mean_d5_raw","mean_d10_raw","mean_d25_raw")
```

```{r}
# Scale the matrix (z-score)
cm2_scaled <- as.data.frame(t(apply(cm2, 1, scale)))
colnames(cm2_scaled) <- colnames(cm2)

cm2_scaled_d1 <- cm2_scaled[,1:4]
cm2_scaled_d5 <- cm2_scaled[,5:8]
cm2_scaled_d10 <- cm2_scaled[,9:11]
cm2_scaled_d25 <- cm2_scaled[,12:14]

cm.list <- list(cm2_scaled_d1,cm2_scaled_d5,cm2_scaled_d10,cm2_scaled_d25)
cm.list <- lapply(cm.list, function(x){x$mean <- rowMeans(x);return(x)})

means <- as.data.frame(sapply(cm.list,function(x){x$mean}),)

rownames(means) <- rownames(cm.list[[1]])
colnames(means) <- c("mean_d1_scaled","mean_d5_scaled",
                     "mean_d10_scaled","mean_d25_scaled")

# The degeneslist contains dataframes for the DE genes from the results.list which are part of the countmatrix
results.list2 <- lapply(results.list, na.omit) #NAs need to be removed prior

degeneslist <- lapply(results.list2,function(x){
  x[abs(x$log2FoldChange) > 1 & x$padj < 0.05 & x$symbol %in% 
      rownames(cm2),]}
  )
```

# Define the patterns

```{r}
# A pattern contains 3 letters
# We compare the scaled means. If the mean of day1 is higher than day5,
# the gene is down regulated.
letter1_tf <- means$mean_d1_scaled > means$mean_d5_scaled

letter1 <- rep("U",nrow(means))
letter1[letter1_tf] <- "D"
letter1[which(rownames(means) %ni% 
                degeneslist$d01_d05$symbol)] <- "N"

# DE 5/10
letter2_tf <- means$mean_d5_scaled > means$mean_d10_scaled

letter2 <- rep("U",nrow(means))
letter2[letter2_tf] <- "D"
letter2[which(rownames(means) %ni% 
                degeneslist$d05_d10$symbol)] <- "N"

# DE 10/25
letter3_tf <- means$mean_d10_scaled > means$mean_d25_scaled

letter3 <- rep("U",nrow(means))
letter3[letter3_tf] <- "D"
letter3[which(rownames(means) %ni% 
                degeneslist$d10_d25$symbol)] <- "N"

# Add the letter to the data frame
means$pattern <-paste0(letter1,letter2,letter3)
```

## Special cases NN[UD]/[UD]NN
```{r}
# we add to new comparisons: if the pattern is NN[UD]/[UD]NN we check 
# in the results of d1vsd10/ [d1vsd25/d5vsd25]
# degeneslist contains all comparisons
# is it high between d10 and d5 
# if letter 1+2 == N then check d1vsd10
# if it is in the list then call it sUU instead of NNU

means$pattern_new <- means$pattern

# take into account that you have two Ns in a row, only check them

means_subset_UDNN <- means[grep("[UD]NN",means$pattern),]
means_subset_NNDU <- means[grep("NN[UD]",means$pattern),]

# check for [UD]NN if they are maybe contained in the other DE genes
# NN[DU] means N in d01vsd05 and neutral in d10vsd05, but UP/DOWN in  d10vsd25. 
# We know that they are not part of d1vsd5 or d5vs10 as they are neutral

letter1_NNDU<-rep("NN",nrow(means_subset_NNDU))

letter1_NNDU[which(rownames(means_subset_NNDU) %in% 
                     degeneslist$d10_d01[degeneslist$d10_d01$log2FoldChange > 1,"symbol"])] <- "sU"

letter1_NNDU[which(
  rownames(means_subset_NNDU) %in%
    degeneslist$d10_d01[
      degeneslist$d10_d01$log2FoldChange < 1,"symbol"])] <- "sD"

#Make the third letter which know must either be up or down
letter3_NNDU_tf <- means_subset_NNDU$mean_d10_scaled > 
  means_subset_NNDU$mean_d25_scaled

letter3_NNDU <- rep("U",nrow(means_subset_NNDU))
letter3_NNDU[letter3_NNDU_tf] <- "D"

#Check for [UD]NN if they are maybe contained in the other DE genes
letter3_UDNN<-rep("NN",nrow(means_subset_UDNN))

letter3_UDNN[which(
  rownames(means_subset_UDNN) %in%
    degeneslist$d25_d05[
      degeneslist$d25_d05$log2FoldChange > 1,"symbol"])] <- "sU"

#Small Down
letter3_UDNN[which(
  rownames(means_subset_UDNN) %in%
    degeneslist$d25_d05[
      degeneslist$d25_d05$log2FoldChange < 1,"symbol"])] <- "sD"

#comment: the code below is not necessary in this case, as all genes already have been annotated by the first sU/sD

#letter3_UDNN[which(rownames(means_subset_UDNN) %in% degeneslist$d25_d05[degeneslist$d25_d05$log2FoldChange > 1,"symbol"])]<-"sU"
#letter3_UDNN[which(rownames(means_subset_UDNN) %in% degeneslist$d25_d05[degeneslist$d25_d05$log2FoldChange < 1,"symbol"])]<-"sD"

#make the first letter which we know must either be up or down
letter1_UDNN_tf <- means_subset_UDNN$mean_d1_scaled > 
  means_subset_UDNN$mean_d5_scaled

letter1_UDNN <- rep("U",nrow(means_subset_UDNN))
letter1_UDNN[letter1_UDNN_tf] <- "D"

#combine
means_subset_UDNN$pattern_new <- paste0(letter1_UDNN,letter3_UDNN)
means_subset_NNDU$pattern_new <- paste0(letter1_NNDU,letter3_NNDU)

means_new <- rbind(means_subset_UDNN,means_subset_NNDU)

means_new <- rbind(means_new,means[rownames(means) %ni% 
                                     rownames(means_new),])

#look that they are in the same order as the cm2 for later
means_new <- means_new[rownames(cm2),]

means.split.new <- split(means_new,f = means_new$pattern_new)

#Combine together the count matrix and the scaled means and the pattern into one table to export
cm2meanspattern <- cbind(cm2,means_raw,means_new)

cm2meanspattern$pattern_old <- cm2meanspattern$pattern
cm2meanspattern$pattern <- NULL

cm2meanspattern.split <- split(cm2meanspattern,
                               f = cm2meanspattern$pattern_new)
```

### Transformations for the tempDE plot
```{r}
#Very messy and ugly code, but it works...
means_for_plot <- means_new %>% arrange(pattern_new)

plot_df <- melt(data = t(means_for_plot[1:4]))

pattern_rep <- as.data.frame(table(means_new$pattern_new))
pattern_rep$parentheses <- paste0("(", pattern_rep$Freq, ")")
pattern_rep$Var1 <- pattern_rep[c(1,3)] %>% unite(new,sep = " ")

pattern_list<-rep(list(NA),nrow(pattern_rep))
pattern_freq<-rep(list(NA),nrow(pattern_rep))
for(i in 1:nrow(pattern_rep))
  {
  pattern_list[[i]]<-rep(pattern_rep[i,1],4*pattern_rep[i,2])
  pattern_freq[[i]]<-rep(pattern_rep[i,2],4*pattern_rep[i,2])
}

plot_df <- cbind(plot_df,unlist(pattern_list),unlist(pattern_freq))
colnames(plot_df) <- c("timepoint","gene","expression","pattern","n.elements")
levels(plot_df$timepoint) <- c("d01","d05","d10","d25")

#we consider only patterns with at least 30 elements
plot_df <- plot_df[plot_df$n.elements >= go.cutoff,]
```

### Save results
```{r}
# Step 1: Define colors for each segment based on individual letters in the pattern
plot_df <- plot_df %>%
  # Split pattern into individual letters
  mutate(segment_1 = str_sub(pattern, 1, 1),
         segment_2 = str_sub(pattern, 2, 2),
         segment_3 = str_sub(pattern, 3, 3)) %>%
  # Assign colors based on each segment
  mutate(color_1 = case_when(segment_1 == "U" ~ pos_color,
                             segment_1 == "N" ~ "grey",
                             segment_1 == "D" ~ neg_color),
         color_2 = case_when(segment_2 == "U" ~ pos_color,
                             segment_2 == "N" ~ "grey",
                             segment_2 == "D" ~ neg_color),
         color_3 = case_when(segment_3 == "U" ~ pos_color,
                             segment_3 == "N" ~ "grey",
                             segment_3 == "D" ~ neg_color))

# Step 2: Create a new data frame for each segment transition
plot_df_segments <- plot_df %>%
  group_by(gene) %>%
  # Add next timepoint and expression for segments
  mutate(next_timepoint = lead(timepoint),
         next_expression = lead(expression)) %>%
  # Remove last rows as they have no "next" segment
  filter(!is.na(next_timepoint)) %>%
  # Assign colors to each segment based on timepoint position
  mutate(segment_color = case_when(
    timepoint == "d01" ~ color_1,
    timepoint == "d05" ~ color_2,
    timepoint == "d10" ~ color_3
  ))
```


```{r}
# Step 3: Plot using geom_segment() with individual segment colors
temp.de_plot <- ggplot(plot_df_segments, aes(x = timepoint, y = expression, group = gene)) +
  geom_segment(aes(xend = next_timepoint, yend = next_expression, color = segment_color), 
               linewidth = 0.25) +
  scale_color_identity() +  # Use colors as defined in the data
  theme_bw() +
  scale_x_discrete(expand = c(0, .01)) +
  scale_y_continuous(breaks = seq(-2, 2, 1), position = "left") +
  facet_wrap(~fct_reorder(pattern, parse_number(pattern), .desc = TRUE), nrow = 1,
             strip.position = "left") +
  theme(axis.text = element_text(colour = "black",size = 7),
        axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text.y = element_text(size = 6, margin = margin(t = 10)),
        strip.text = element_text(size = 6),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        strip.background = element_blank(),
        strip.placement = "outside",
        panel.spacing.y = unit(0.1,"cm"),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        aspect.ratio = 1)

# Display the plot
print(temp.de_plot)

```


```{r}
fig2_folder <-  file.path(harddrive,"figures/figure_2/saves/")
saveRDS(temp.de_plot,file.path(fig2_folder,"temp_de_plot_A.Rds"))
saveRDS(plot_df,file.path(fig2_folder,"plot_df_fig2.Rds"))

```

```{r}
save_ggplot_formats(
    plt = temp.de_plot,
    create_plot_subdir = TRUE,
    base_plot_dir = plots_folder,
    plt_name = glue("temporal_de_genes_{NAME}_vertical"),
    height = 2,width = 11
  )
```

```{r}
#All patterns in one sheet
write.xlsx(cm2meanspattern,file =
             file.path(charts_folder,
                       glue("temporal_de_genes_{NAME}.xlsx")),
           rowNames = TRUE)

#Each pattern in a separate sheet
write.xlsx(cm2meanspattern.split,file.path(charts_folder,
                                           glue("temporal_de_genes_pattern_split_{NAME}.xlsx")),
           rowNames = TRUE)
```

# Temp DE Heatmap

```{r}
cm2_heatmap <- cm2meanspattern[1:ncol(cm2)]

timepoint <- as.factor(str_remove(colnames(cm2_scaled),"_+[1-9]"))

#col_fun1 <- colorRamp2(c(-4, 0, 4), c(neg_color, "white", pos_color))
col_fun2 <- colorRamp2(c(-2, 0, 2), c(neg_color, "white", pos_color))
#col_fun3 <- colorRamp2(c(-2, 0, 4), c(neg_color,"white", pos_color))

heatmap.plt <- Heatmap(
  as.matrix(cm2_scaled),
  cluster_rows = TRUE,
  cluster_columns = FALSE,
  column_split = timepoint,
  column_title_gp = gpar(fontsize = 6),      # Column title font size
  column_title_side = "bottom",
  show_column_names = FALSE,
  show_row_names = FALSE,
  use_raster = TRUE,
  raster_quality = 10,
  col = col_fun2,
  heatmap_legend_param = list(
    title = "z-score",
    legend_direction = "vertical",
    legend_width = unit(0.5, "cm"),  # Adjust legend width
    labels_gp = gpar(fontsize = 6),# Legend labels font size
    title_gp = gpar(fontsize = 6)  # Legend title font size
  ),
  show_row_dend = FALSE
)

heatmap.plt2 <- draw(heatmap.plt,heatmap_legend_side = "right")
saveRDS(heatmap.plt2,file.path(fig2_folder,"temp_de_heatmap.Rds"))

```

```{r}
save_ggplot_formats(
  plot_obj = "heatmap",
  plt = heatmap.plt2,
  base_plot_dir = fig2_plots_folder,
  plt_name = "figure2_heatmap",
  width = 6,
  height = 6,
  units = "cm"
)
```

# Fisher test blimp/mafb
```{r}
blimp_up_anno <- fisher_dataframe(countmatrix,
                                  cm2meanspattern.split,
                                  blimp.up)

blimp_down_anno <- fisher_dataframe(countmatrix,
                                    cm2meanspattern.split,
                                    blimp.down)

mafb_up_anno <- fisher_dataframe(countmatrix,
                                 cm2meanspattern.split,
                                 mafb.up)

mafb_down_anno <- fisher_dataframe(countmatrix,
                                   cm2meanspattern.split,
                                   mafb.down)
```

## fishertest heatmap
```{r}

temp_de_levels <- levels(fct_reorder(plot_df_segments$pattern, parse_number(plot_df_segments$pattern)))

temp_de_levels <- str_sub(temp_de_levels,1,3)
temp_de_levels <- c("UNU",temp_de_levels[-2])

# Prepare blimp_df with combined p-values and set column names
blimp_df <- bind_cols(
  blimp_up = blimp_up_anno$p_val_adj,
  blimp_down = blimp_down_anno$p_val_adj,
  mafb_up = mafb_up_anno$p_val_adj,
  mafb_down = mafb_down_anno$p_val_adj,
  pattern = rownames(blimp_down_anno)
)

# Set rownames directly and reorder blimp_df based on the pattern levels
factor_levels <- fct_reorder(plot_df$pattern, parse_number(plot_df$pattern))

# Filter rows based on factor_levels prefix and apply -log10 transformation
blimp_df <- blimp_df %>% filter(pattern %in% substr(factor_levels, 1, 3)) 

blimp_df[, 1:4] <- -log10(blimp_df[, 1:4])

blimp_df <- blimp_df %>%
  mutate(pattern = factor(pattern, levels = temp_de_levels)) %>%
  arrange(pattern)

# Prepare data: Reshape blimp_df_log into long format
heatmap_df <- as.data.frame(blimp_df) %>%
  pivot_longer(cols = -pattern, names_to = "Condition", values_to = "Log_padj")

# Adjust infinite values if needed
heatmap_df <- heatmap_df %>%
  mutate(Log_padj = ifelse(Log_padj == Inf,
                           max(Log_padj[is.finite(Log_padj)]), Log_padj))

heatmap_df$Condition <- as.factor(heatmap_df$Condition)
levels(heatmap_df$Condition) <- c("Down with BLIMP1", "Up with BLIMP1",
                                  "Down with MAFB","Up with MAFB")
```


```{r}
# Adjust the aspect ratio to match cell height to facet height
heatmap_plot <- ggplot(heatmap_df, aes(
  x = fct_relevel(Condition, 
                  c("Up with BLIMP1", "Down with BLIMP1", 
                    "Up with MAFB", "Down with MAFB")), 
  y = pattern, fill = Log_padj)) +
  geom_tile(color = "black", height = 1,width = 0.1) +  # Adjust cell dimensions here
  scale_fill_gradientn(
    colors = c("white", "#C7E9C0", "#A1D99B", "#74C476",
               "#41AB5D", "#238B45", "#006D2C", "#00441B"),
    values = scales::rescale(c(-log10(0.05), 2, 5, 10, 20, 40, 80, 160)),
    name = "-log10 (p.adj.)"
  ) +
  theme_minimal(base_size = 7) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1,size = 7),
    #axis.text.y = element_text(size = 7),
    axis.text.y = element_blank(),
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    panel.grid = element_blank(),
    panel.spacing = unit(0,"cm")
    #panel.spacing.y = unit(0.1, "cm"),
    #aspect.ratio = 0.1
  ) +
  scale_x_discrete(expand = c(0, 0)) +  
  scale_y_discrete(expand = c(0, 0)) +  
  coord_fixed() +
  labs(x = NULL, y = NULL) 

print(heatmap_plot)
#saveRDS(blimp_hm,file.path(fig2_folder,"blimp_heatmap.Rds"))
```

```{r}
combined_plot <- temp.de_plot + heatmap_plot +
  plot_layout(widths = c(1, 1)) & theme(plot.margin = unit(c(0,0,0,0),"cm")) # Adjust the widths as needed
```

```{r}
save_ggplot_formats(plt = combined_plot,
                    base_plot_dir = fig2_plots_folder,
                    width = 16,
                    height = 16,
                    plt_name = "temp_de_fig2",
                    units = "cm")
```

# Gene Ontology analysis
```{r}
go_plots_folder <- file.path(harddrive,analysis_folder,"tempDE/GO/plots")
go_charts_folder <- file.path(harddrive,analysis_folder,"tempDE/GO/charts")

if (!dir.exists(go_plots_folder)){
  dir.create(go_plots_folder,recursive = TRUE)
  dir.create(go_charts_folder,recursive = TRUE)
}

sapply(means.split.new,nrow)

means.split.GO <- means.split.new[sapply(means.split.new,nrow) >= go.cutoff]
```

## GO Dotplot Patterns
```{r}
means.split.GO <- means.split.new[sapply(means.split.new,nrow) >= go.cutoff]

means.split.GO_filter <- means.split.GO[names(means.split.GO) %in%
                                          c("NNU","NND","UNN","DNN")]

GO_means_genes <- lapply(means.split.GO_filter,rownames)

# Compare clusters
GO_means_compare <- compareCluster(GO_means_genes,
                               fun = "enrichGO",
                               OrgDb = "org.Mm.eg.db",
                               keyType = "SYMBOL",
                               ont = ont,
                               pAdjustMethod = "BH",
                               pvalueCutoff  = p.cutoff,
                               #qvalueCutoff = 1,
                               readable = TRUE
                               )
```

```{r}
count.cutoff <- 5 #This is to keep Wnt inside

topN <- 5
```

```{r}
process_and_plot(
    GO_means_compare,
    NAME = "GO_temp_DE", 
    count.cutoff = count.cutoff, 
    topN = topN, 
    plots_folder = plots_folder, 
    charts_folder = charts_folder, 
    save_plot = TRUE,     # Save the plot
    save_formats = TRUE  # Save as both CSV and Excel
  )
```


```{r}
# Filter and arrange by p.value
GO_means_compare_filter <- filter(GO_means_compare, 
                                  Count > count.cutoff) %>%
  arrange(p.adjust)

# -log of p.value
GO_means_compare_filter@compareClusterResult$p.adjust <- -log10(
  GO_means_compare_filter@compareClusterResult$p.adjust )
```

## Plotting
```{r}
# make data frames for plotting. Only use topN terms per Cluster
df_means <- fortify(GO_means_compare_filter, 
                           showCategory = topN, split = NULL)
df_means <- droplevels(df_means)

x_labels_means <- gsub("\n"," ",levels(df_means$Cluster))

levels(df_means$Cluster) <- x_labels_means
```

## Row clustering
```{r}
clust_met <- "complete"

markers.means <- df_means$Description %>% unique()

p.mat.means <- df_means %>% 
  filter(Description %in% markers.means) %>% 
  select(Description,Cluster,p.adjust) %>%
  pivot_wider(names_from = Cluster,values_from = p.adjust) %>%
  data.frame() # make df
row.names(p.mat.means) <- p.mat.means$Description  # put gene in `row`
p.mat.means <- p.mat.means[,-1] #drop gene column as now in rows
p.mat.means[is.na(p.mat.means)] <- 0

# hclust with distance matrix
clust.means <- hclust(dist(p.mat.means %>% as.matrix()),method = clust_met) 
```

## Plotting
```{r}
df_means_rc <- df_means

df_means_rc$Description <- fct_relevel(df_means_rc$Description,
                                rev(clust.means$labels[clust.means$order]))
df_means_rc$Description_trunc <- sapply(df_means_rc$Description, truncate_go_term, 
                                        max_length = 60)

df_means_rc$ID_desc <- paste(df_means_rc$ID,
                                df_means_rc$Description_trunc)

df_means_rc$FoldEnrichment <- df_means_rc$GeneRatio/parse_ratio(df_means_rc$BgRatio)
  
theme.dp <- list(
  geom_point(),
  theme_dose(7),
  coord_fixed(ratio = 1),
  #adjust limits
  scale_color_gradient(low = pos_color_low, high = pos_color),
  scale_size_continuous(),  #adjust limits
  ylab(NULL),
  theme(text = element_text(size = 7),
    axis.title = element_blank(),
        axis.text.x = element_text(angle = 90,
                                   hjust = 1, 
                                   vjust = .5
                                   ),
        legend.text = element_text(size = 7),
    legend.position = c(2,-0.11), # GO
        #legend.position = c(3,-0.1), # kegg
        #legend.position = c(2.5,-0.1), # reactome
        legend.direction = "horizontal",
        legend.box = "vertical",
        legend.spacing.x = unit(0.05, 'cm')
  ),
  labs(color = "-log10 (p.adjust)"),
  guides(size = guide_legend(order = 2),
         color = guide_colorbar(order = 1)
         )
  )

dp_means_rc <- ggplot(df_means_rc, aes(x = Cluster, y = reorder(ID_desc, p.adjust), 
                               size = FoldEnrichment, color = p.adjust)) +
  theme.dp + ggtitle(element_blank()) + scale_y_discrete(position = "right") + theme(legend.position = "none")

#saveRDS(dp_means_rc,file.path(fig2_folder,"go_dotplot_tempde.Rds"))
```

```{r}
save_ggplot_formats(
  plt = dp_means_rc,
  create_plot_subdir = TRUE,
  base_plot_dir = plots_folder,
  plt_name = "GO_dotplot.means_rc_new_2024_08_08_filter_nolegend",
  width = 3.8,height = 4.2
  )
```
