---
title: "single_cell_manual_analysis"
author: "Johannes Schöneich"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries
```{r}
library(Seurat)
library(tidyverse)
library(ggsci)
library(Hmisc)
library(archive)
library(scales)
library(gridExtra)
library(glue)
library(patchwork)
library(scCustomize)
```

# Adjustments
```{r}
harddrive <- "H:"

source(file.path(harddrive,"helper_functions.R"))
#custom themes

source(file.path(harddrive,"scrna_datasets/single_cell_themes.R"))
source(file.path(harddrive,"scrna_datasets/save_load_helper.R"))

analysis_folder <- file.path(harddrive,
                          "scrna_datasets/scrna_both_d25/scrna_full_2024_both_d25_eec")

cluster_use <- "harmony_inte_clusters"
```

```{r}
scrna_eec <- load_object(file.path(analysis_folder,
                                            "/save/scrna_phase_clustering.Rds"))

# scrna_old <- load_object(file.path(analysis_folder,
#                                             "/save/scrna_eec_inf.Rds"))

plots_folder <- file.path(analysis_folder,"analysis/plots")

charts_folder <- file.path(analysis_folder,"analysis/charts/")
```

```{r}
GO_save_folder <- file.path(analysis_folder,"saves/")

pathway_save_folder <- file.path(analysis_folder,"Pathway/saves/")

# Which ontology: choose between all, biological process (bp), 
# molecular function (mf) and cellular component (cc).
ont <- "bp"

# P-adjust cutoff. Adjustment method is benjamini-hochberg (FDR)
p.cutoff <- 0.05

# The number of GO terms to compare
topN  <- 10

# Count cutoff. The low end filtering of counts
count.cutoff <- 10

# Heatmap coloring options
pos_color_low <- "#fff5f0"
pos_color_high <- "#E41A1C" # The color to which the significant p-values converge

neg_color_low <- "#F7FBFF"
neg_color_high <- "#377EB8"


inf_cols <- c("#E08B00","#5BB300","#00C0AF","#7997FF","#FF61C9")
uninf_cols  <- c("#E08B00","#5BB300","#7997FF","#FF61C9")
```

```{r}
"Xist" %in% rownames(scrna_eec) #if FALSE, its correct.

DimPlot(scrna_eec, reduction = "harmony_UMAP", 
                group.by = "harmony_inte_clusters",
                label = TRUE) + ggtitle(element_blank()) & mini_umap_theme

DimPlot(scrna_eec, reduction = "harmony_UMAP", 
                group.by =  "name",
                label = FALSE)

Idents(scrna_eec) <- "name"
scrna_eec_uninf <- subset(scrna_eec,idents = "d05i", invert = TRUE)
```

```{r}
save_object(scrna_eec,file.path(analysis_folder,"scrna_eec_both_d25.Rds"))

save_object(scrna_eec_uninf,file.path(analysis_folder,
                                      "scrna_uninf_both_d25_eec.Rds"))
```

```{r}
scrna_eec <- load_object(file.path(analysis_folder,"scrna_eec_both_d25.Rds"))

scrna_eec_uninf <- load_object(file.path(analysis_folder,
                                         "scrna_eec_uninf_both_d25.Rds"))
```

```{r, fig.width = 30}
#TODO bring order into the chaos


# Define a function to generate the plots
generate_split_plot <- function(i, scrna, cols, levels) {
  current_level <- levels[i]
  #cell_number <- table(scrna$harmony_inte_clusters)[i] # TODO: fix for automation
#  cell_number <- table(scrna$name)[i] # TODO: fix for automation
  cols.highlight <- cols[i]
  title <- glue("{current_level}") # ({cell_number})")
  DimPlot(scrna, 
          label = FALSE, 
          reduction = "harmony_UMAP", 
          cells.highlight = WhichCells(scrna, idents = current_level),
          cols.highlight = cols.highlight,
          cols = "lightgrey",
          sizes.highlight = 1) +
    ggtitle(title) + mini_umap_theme & NoLegend() 
} 


Idents(scrna_eec) <- cluster_use

scrna_eec$harmony_inte_clusters <- as.factor(scrna_eec$harmony_inte_clusters)
scrna_eec$harmony_inte_clusters <- droplevels(scrna_eec$harmony_inte_clusters)
levels(scrna_eec$harmony_inte_clusters) <- 0:5


Idents(scrna_eec) <- "sub_annotation"

scrna_eec <- RenameIdents(scrna_eec, 
                          "SLN" = "SLN cells",
             "Enterochromaffin" = "Enterochromaffin",
             "K" = "K cells", 
             "I"= "I cells",
             "EC-Reg4" = "EC-Reg4",
             "D" = "D cells"
             )
#plot_levels <- levels(scrna_eec$harmony_inte_clusters)
plot_levels <- levels(Idents(scrna_eec))

levels(scrna_eec$sub_annotation) <- levels(Idents(scrna_eec))

eec_cols <- c("#A3A500", "#FFFF00", "#FFAA00", "#D4A017", "#C68000", "#6E4F00")

# Generate a list of plots
plot_list_sc <- lapply(seq_along(plot_levels), 
                    generate_split_plot, 
                    scrna = scrna_eec, 
                    levels = plot_levels,
                    cols = eec_cols
                    )

my_grid <- wrap_plots(plot_list_sc, nrow = 1)
```

```{r, fig.width = 30}

plots_folder = file.path(harddrive,"figures/figure_6")

save_ggplot_formats(
  plt = my_grid,
  base_plot_dir = plots_folder,
  plt_name = "grid_harmony_eec_v2",
  width = 12, height = 3
)
```


```{r, fig.width = 30}

my_grid_vertical <- wrap_plots(plot_list_sc,ncol = 2)

save_ggplot_formats(
  plt = my_grid_vertical,
  base_plot_dir = plots_folder,
  plt_name = "grid_harmony_eec_vertical",
  width = 6, height = 8
)
```

```{r, fig.width = 30}
scrna_eec$name <- as.factor(scrna_eec$name)

Idents(scrna_eec) <- "name"
# Generate a list of plots
plot_list_stage <- lapply(seq_along(levels(scrna_eec$name)), 
                    generate_split_plot, 
                    scrna = scrna_eec, 
                    levels = levels(scrna_eec$name),
                    cols = inf_cols
                    )

plot_list_stage[[6]] <- DimPlot(scrna_eec, 
                                reduction = "harmony_UMAP", group.by = "name") + 
  ggtitle(glue("All ({sum(table(scrna_eec$name))})")) & mini_umap_theme 


stage_grid <- wrap_plots(plot_list_stage)


save_ggplot_formats(
  plt = stage_grid,
  base_plot_dir = plots_folder,
  plt_name = "grid_stage_eec2",
  width = 16, height = 12
)
```

```{r}
cluster_use <- "RNA_snn_res.0.6"
Idents(scrna_eec_uninf) <- "RNA_snn_res.0.6"

haber_markers_gpcr <- c(
  "Vipr1", "Ffar2", "Gper1", "Gpr119", "Gpbar1", 
  "Ptger3","Galr1", "Cnr1", "Ffar4", "Adgrd1", "Ffar1","Iapp","Nucb2"
)

haber_fig3 <- c("Sox4","Neurog3","Neurod2","Sct","Cck","Gcg",
                "Ghrl","Gal","Gip","Sst","Nts","Tac1","Tph1","Reg4")

haber_markers_extended <- c("Neurog3","Sct","Tac1","Sst","Cck","Gcg","Ghrl",
                            "Gip","Nts","Reg4","Pyy")

haber_hm <- c("Sc1","Cck","Tac1","Tph1","Reg4","Gcg","Pyy","Gip","Ghrl","Sst","Nts","Gal")
all_haber_markers <- sort(unique(c(haber_markers_gpcr,haber_fig3,haber_markers_extended)))

fp <- FeaturePlot(
  object = scrna_eec_uninf,
  pt.size = 1,
  label = TRUE,
  features = all_haber_markers,
  reduction = "harmony_UMAP",
  order = TRUE,
  cols = c("lightgrey", "red"),
  ncol = 4,
  max.cutoff = "q95"
) & fp_theme

vp <- VlnPlot(scrna_eec_uninf,
        features = all_haber_markers,
        group.by = cluster_use,
        ncol = 4,
        pt.size = 0,
        sort = FALSE
        ) & theme(axis.title.x = element_blank())

dp_eec <- DotPlot_scCustom(
      seurat_object = scrna_eec_uninf,
      features = all_haber_markers,
      group.by = cluster_use,
      assay = "RNA",
      colors_use = viridis_plasma_dark_high,
      x_lab_rotate = TRUE
      ) + theme(legend.text = element_text(size = 12),
                #legend.key.size = element_text(size = 20),
                legend.title = element_text(size = 12),
        axis.text.x  = element_text(size = 12),
        axis.text.y = element_text(size = 12)
        )

reg4_tac1_fp <- FeaturePlot(scrna_eec_uninf,
                            features = c("Reg4", "Tac1"),
                            pt.size = 1,
  label = TRUE,
  reduction = "harmony_UMAP",
  order = TRUE,
  max.cutoff = "q95",
  blend = TRUE) & fp_theme


#names c5: sst (D Cells), 1 = tac1 (Enterochromaffin Cells) 4 = reg4 (EC-Reg4),
# 3=cck (I cells), 2= Gip (K Cells), 0 = Sct,Nts,Pyy (SLN Cells)
# 


#names new 
# 0 = Tac1 +Reg4 (EC Reg4)
# 1 = Nts (SIN)
# 2 = Pyy (SIL-P) 
# 3 = Gip (SIK Cells)
# 4 = Sct, Cck, Ghrl (SILA)
# 5 = (EC)
# 6 = Sst and Iapp (SAKD Cells) 
```

```{r}
cluster_use <-  "sub_annotation"
markers_new <- c("Reg4", "Tac1","Tph1","Nts","Pyy","Sct",
                 "Gip","Cck","Sst","Iapp","Ghrl")

fp_new_marker <- FeaturePlot(
  object = scrna_eec_uninf,
  pt.size = 1,
  label = TRUE,
  features = markers_new,
  reduction = "harmony_UMAP",
  order = TRUE,
  cols = c("lightgrey", "red"),
  ncol = 2,
  max.cutoff = "q95"
) & fp_theme

vp_new_marker <- VlnPlot(scrna_eec_uninf,
        features = markers_new,
        group.by = cluster_use,
        ncol = 4,
        pt.size = 0,
        sort = FALSE
        ) & theme(axis.title.x = element_blank())

dp_new_marker <- DotPlot_scCustom(
      seurat_object = scrna_eec_uninf,
      features = markers_new,
      group.by = cluster_use,
      assay = "RNA",
      colors_use = viridis_plasma_dark_high,
      x_lab_rotate = TRUE
      ) + theme(legend.text = element_text(size = 12),
                #legend.key.size = element_text(size = 20),
                legend.title = element_text(size = 12),
        axis.text.x  = element_text(size = 12),
        axis.text.y = element_text(size = 12)
        )

save_ggplot_formats(
  plt = fp_new_marker,
  base_plot_dir = plots_folder,
  plt_name = "fp_haber_haber_final_markers2",
  width = 8, height = 12
)

save_ggplot_formats(
  plt = vp_new_marker,
  base_plot_dir = plots_folder,
  plt_name = "vp_haber_haber_final_markers2",
  width = 12, height = 4
)

save_ggplot_formats(
      plt = dp_new_marker,
      base_plot_dir = plots_folder,
      plt_name = "dp_haber_haber_final_markers_sub_annotation",
      width = 6,
      height = 3.5
)
```

```{r}
scrna_eec_uninf$sub_annotation <- scrna_eec_uninf$RNA_snn_res.0.6

Idents(scrna_eec_uninf) <- "sub_annotation" 

new_names <- c("EC–Reg4","SIN","SIL-P","SIK","SILA","EC","SAKD")
names(new_names) <- levels(scrna_eec_uninf)

scrna_eec_uninf <- RenameIdents(scrna_eec_uninf,new_names)

levels(scrna_eec_uninf$sub_annotation) <- new_names

eec_umap <- DimPlot(scrna_eec_uninf, reduction = "harmony_UMAP", cols = "Set3") & mini_umap_theme
eec_umap_name <- DimPlot(scrna_eec_uninf, reduction = "harmony_UMAP", group.by = "name") & mini_umap_theme & ggtitle(element_blank())
```

```{r}
save_ggplot_formats(
  plt = eec_umap,
  base_plot_dir = plots_folder,
  plt_name = "eec_umap",
  width = 4.5, height = 4
)

save_ggplot_formats(
  plt = eec_umap_name,
  base_plot_dir = plots_folder,
  plt_name = "eec_umap_name",
  width = 7, height = 6
)
```


```{r}
save_ggplot_formats(
  plt = fp,
  base_plot_dir = plots_folder,
  plt_name = "fp_haber_all_haber",
  width = 16, height = 12
)

save_ggplot_formats(
  plt = vp,
  base_plot_dir = plots_folder,
  plt_name = "vp_haber_all_haber",
  width = 12, height = 8
)

save_ggplot_formats(
      plt = dp_eec,
      base_plot_dir = plots_folder,
      plt_name = "dotplot_haber_all_haber",
      width = 8,
      height = 3.5
)
```
