---
title: "GO_dotplot_cv"
author: "Johannes Schöneich"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries
```{r}
library(clusterProfiler)
library(enrichplot)
library(DOSE)
library(tidyverse)
library(glue)
library(limma)
library(stringi)
library(ReactomePA)
```

# Adjustments
```{r}
harddrive  <- "D:/231248/NTFS_3.64TB" 

source(file.path(harddrive,"helper_functions.R"))
source(file.path(harddrive,"DE_analysis/DE_helperfunctions.R"))


analysis_folder <- file.path(harddrive,
                             "DE_analysis/DE_LRT_crypt_villus_group/")

results.list <- readRDS(file.path(analysis_folder,
                                  "DE_results.list_group.Rds"))

# Which ontology: choose between all, biological process (bp), 
# molecular function (mf) and cellular component (cc).
ont <- "bp"

# P-adjust cutoff. Adjustment method is benjamini-hochberg (FDR)
p.cutoff <- 0.05

plots_folder <- file.path(analysis_folder,"GO/plots")
charts_folder <- file.path(analysis_folder,"GO/charts")

GO_save_folder <- file.path(analysis_folder,
                          "GO/saves/")
pathway_save_folder <- file.path(analysis_folder,
                          "Pathway/saves/")

# The number of GO terms to compare
topN <- 4

# Count cutoff. The low end filtering of counts
count.cutoff <- 10

# Heatmap coloring options
pos_color_low <- "#fff5f0"
pos_color_high <- "#E41A1C" # The color to which the significant p-values converge

neg_color_low <- "#F7FBFF"
neg_color_high <- "#377EB8"

# One of GO, KEGG, Reactome or all
# if you choose all, you need to loop through them manually 
# See lines 160/161 for this
comparison <- "GO"

#analysis name for plot names
NAME <- glue("GO_FE_top_{topN}")

cv.names <- c("d01.crypts_d05.crypts","d05.crypts_d10.crypts",
              "d10.crypts_d25.crypts","d01.villi_d05.villi",
              "d05.villi_d10.villi","d10.villi_d25.villi")

results.list_filter <- results.list[names(results.list) %in% cv.names]
```

# Functions
```{r}
add_missing_names <- function(df,missing_names,geneClusters, sort = TRUE){
  if(!is_empty(missing_names)){
      # function that takes as input a fortified data.frame
      # the missing names from the analysis 
      # and the geneClusters from the GO output
      missing_length <- sapply(geneClusters[
        names(geneClusters) %in% missing_names],length)
      
      missing_names <- glue("{names(missing_length)} ({missing_length})")
      
      n_cols <- ncol(df)
      
      # Create a new data frame with the same number of columns as the df
      new_rows <- data.frame(matrix(NA, nrow = length(missing_names),
                                    ncol = n_cols))
      # Set the values from vector missing_names in the first column
      new_rows[, 1] <- missing_names 
      
      # Rename the columns of new_rows to match your original data frame
      colnames(new_rows) <- colnames(df)
      new_rows$Description <- df$Description[1:length(missing_names)]
      new_rows$ID <- df$ID[1:length(missing_names)]

      # Combine the new data frame with your existing data frame
      df <- rbind(df, new_rows)
      }
  if(sort == TRUE){
    df$Cluster <- fct_relevel(df$Cluster,c(
      sort(grep("crypt",levels(df$Cluster),value = TRUE)),
      sort(grep("villi",levels(df$Cluster),value = TRUE))
    ))
  }
  return(df)
}
```

```{r}
# Function to truncate a GO term to the last space before maximum length
truncate_go_term <- function(term,max_length = 33){
    term <- as.character(term)
    # Check if the term length is already within the limit
    if (nchar(term) <= max_length) {
      return(term)
    } else {
      # Find the last space before the maximum length
      last_space <- max(gregexpr("\\s", substr(term, 1, max_length))[[1]])
      truncated_term <- substr(term, 1, last_space - 1)
      return(paste0(truncated_term, "[...]"))
    }
  }
```

# Get significant genes
```{r}
res_up <- lapply(results.list_filter,function(df){
  sigsdf_up <- df[(df$log2FoldChange >= 1) & (df$padj <= 0.05),]
  upgene <- (sigsdf_up$symbol)
  return(upgene)
})

res_down <- lapply(results.list_filter,function(df){
  sigsdf_down <- df[(df$log2FoldChange <= - 1) & (df$padj <= 0.05),]
  downgene <- (sigsdf_down$symbol)
  return(downgene)
})

up_entrez <- lapply(res_up,function(upgene){
  gene_e <- bitr(upgene, fromType="SYMBOL", toType = "ENTREZID", 
                    OrgDb =  "org.Mm.eg.db")
  return(gene_e[["ENTREZID"]])
})

down_entrez <- lapply(res_down,function(downgene){
  gene_e <- bitr(downgene, fromType = "SYMBOL", toType = "ENTREZID", 
                    OrgDb =  "org.Mm.eg.db")
  return(gene_e[["ENTREZID"]])
})
```

# Calculate GO/Pathways and compare cluster
```{r}
if(comparison == "GO"| comparison == "all"){
  up_compare_cv_GO <- compareCluster(res_up,
                             fun = enrichGO,
                             OrgDb = "org.Mm.eg.db",
                             keyType = "SYMBOL",
                             ont = ont,
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(up_compare_cv_GO),
            file = file.path(charts_folder,
                             "up_compare_crypt_villus_GO.csv"),
            row.names = FALSE)
  up_compare_cv <- up_compare_cv_GO
}

if(comparison == "Reactome"| comparison == "all"){
  up_compare_cv_reactome <- compareCluster(up_entrez,
                             fun = enrichPathway,
                             organism = "mouse",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(up_compare_cv_reactome),
            file = file.path(charts_folder,
                             "up_compare_crypt_villus_reactome.csv"),
            row.names = FALSE)
  up_compare_cv <- up_compare_cv_reactome
}

if(comparison == "KEGG"| comparison == "all"){
  up_compare_cv_KEGG <- compareCluster(up_entrez,
                             fun = enrichKEGG,
                             organism = "mmu",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             )
  
  up_compare_cv_KEGG <- setReadable(up_compare_cv_KEGG,
                                    "org.Mm.eg.db",
                                    keyType = "ENTREZID")
  
  up_compare_cv_KEGG@compareClusterResult$Description <- gsub(
      " - Mus musculus \\(house mouse)","",
      up_compare_cv_KEGG@compareClusterResult$Description)
  
  write.csv(as.data.frame(up_compare_cv_KEGG),
            file = file.path(charts_folder,
                             "up_compare_crypt_villus_Kegg.csv"),
            row.names = FALSE)
  up_compare_cv <- up_compare_cv_KEGG
}
```

```{r}
if(comparison == "GO"| comparison == "all"){
  down_compare_cv_GO <- compareCluster(res_down,
                             fun = enrichGO,
                             OrgDb = "org.Mm.eg.db",
                             keyType = "SYMBOL",
                             ont = ont,
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(down_compare_cv_GO),
            file = file.path(charts_folder,
                             "down_compare_crypt_villus_GO.csv"),
            row.names = FALSE)
  down_compare_cv <- down_compare_cv_GO
}

if(comparison == "Reactome"| comparison == "all"){
  down_compare_cv_reactome <- compareCluster(down_entrez,
                             fun = enrichPathway,
                             organism = "mouse",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(down_compare_cv_reactome),
            file = file.path(charts_folder,
                             "down_compare_crypt_villus_reactome.csv"),
            row.names = FALSE)
  down_compare_cv <- down_compare_cv_reactome
}

if(comparison == "KEGG"| comparison == "all"){
  down_compare_cv_KEGG <- compareCluster(down_entrez,
                             fun = enrichKEGG,
                             organism = "mmu",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             )
  
  down_compare_cv_KEGG <- setReadable(down_compare_cv_KEGG,
                                      "org.Mm.eg.db",
                                      keyType = "ENTREZID")
  
  down_compare_cv_KEGG@compareClusterResult$Description <- gsub(
      " - Mus musculus \\(house mouse)","",
      down_compare_cv_KEGG@compareClusterResult$Description)
  
  write.csv(as.data.frame(down_compare_cv_KEGG),
            file = file.path(charts_folder,
                             "down_compare_crypt_villus_Kegg.csv"),
            row.names = FALSE)
  down_compare_cv <- down_compare_cv_KEGG
}
```

# Save results
```{r}
dir.create(GO_save_folder,recursive = TRUE)
dir.create(pathway_save_folder,recursive = TRUE)

saveRDS(down_compare_cv_GO,
        file.path(GO_save_folder,"down_compare_cv_GO.Rds"))
saveRDS(down_compare_cv_KEGG,
        file.path(pathway_save_folder,"down_compare_cv_kegg.Rds"))
saveRDS(down_compare_cv_reactome,
        file.path(pathway_save_folder,"down_compare_cv_reactome.Rds"))

saveRDS(up_compare_cv_GO,
        file.path(GO_save_folder,"up_compare_cv_GO.Rds"))
saveRDS(up_compare_cv_KEGG,
        file.path(pathway_save_folder,"up_compare_cv_kegg.Rds"))
saveRDS(up_compare_cv_reactome,
        file.path(pathway_save_folder,"up_compare_cv_reactome.Rds"))
```

#load results
```{r}
down_compare_cv_GO <- readRDS(file.path(GO_save_folder,
                                        "down_compare_cv_GO.Rds"))
down_compare_cv_KEGG <- readRDS(file.path(pathway_save_folder,
                                          "down_compare_cv_kegg.Rds"))
down_compare_cv_reactome <- readRDS(file.path(pathway_save_folder,
                                              "down_compare_cv_reactome.Rds"))

up_compare_cv_GO <- readRDS(file.path(GO_save_folder,
                                      "up_compare_cv_GO.Rds"))
up_compare_cv_KEGG <- readRDS(file.path(pathway_save_folder,
                                        "up_compare_cv_kegg.Rds"))
up_compare_cv_reactome <- readRDS(file.path(pathway_save_folder,
                                            "up_compare_cv_reactome.Rds"))
```

# Filtering
```{r}
# if you choose all, you need to loop through them manually
up_compare_cv <- up_compare_cv_GO
down_compare_cv <- down_compare_cv_GO

# Filter and arrange by p-value
up_compare_cv_filter <- filter(up_compare_cv,
                                    Count > count.cutoff) %>% arrange(p.adjust)

# -log of adjusted p.value
up_compare_cv_filter@compareClusterResult$p.adjust <- 
  -log10(up_compare_cv_filter@compareClusterResult$p.adjust)

# Filter and arrange by p.value
down_compare_cv_filter <- filter(down_compare_cv,
                                 Count > count.cutoff) %>%
                          arrange(p.adjust)

# -log of p.value
down_compare_cv_filter@compareClusterResult$p.adjust <- -log10(
  down_compare_cv_filter@compareClusterResult$p.adjust )
```

# Maximal and minimal p-values for scales
```{r}
max_p_cv <- max(down_compare_cv_filter@compareClusterResult$p.adjust,
                     up_compare_cv_filter@compareClusterResult$p.adjust)

if(max_p_cv >30){max_p_cv <- 30}

ratios_down_cv <- parse_ratio(
  down_compare_cv_filter@compareClusterResult$GeneRatio) / parse_ratio(down_compare_cv_filter@compareClusterResult$BgRatio)

ratios_up_cv <- parse_ratio(
  up_compare_cv_filter@compareClusterResult$GeneRatio) / parse_ratio(up_compare_cv_filter@compareClusterResult$BgRatio)

max_gr_cv <- max(ratios_down_cv,ratios_up_cv)
min_gr_cv <- min(ratios_down_cv,ratios_up_cv)
```

# Fortify data.frames for plotting (topN)
```{r}
# make data frames for plotting. Only use topN terms per Cluster
df_up_cv <- fortify(up_compare_cv_filter, 
                         showCategory = topN, split = NULL)

df_up_cv <- droplevels(df_up_cv)

df_down_cv <- fortify(down_compare_cv_filter, 
                           showCategory = topN, split = NULL)

df_down_cv <- droplevels(df_down_cv)

# labels adjusted to have whitespace instead of newline
x_labels_up <- gsub("\n"," ",levels(df_up_cv$Cluster))
x_labels_down <- gsub("\n"," ",levels(df_down_cv$Cluster))

levels(df_up_cv$Cluster) <- x_labels_up
levels(df_down_cv$Cluster) <- x_labels_down

# add missing names
missing_cv_up <- cv.names[cv.names %ni% 
                            strsplit2(unique(df_up_cv$Cluster)," ")[,1]]

missing_cv_down <- cv.names[cv.names %ni%
                              strsplit2(unique(df_down_cv$Cluster)," ")[,1]]

df_up_cv_mn <- add_missing_names(df_up_cv,
                                 missing_cv_up,
                                 up_compare_cv@geneClusters
                                 )

df_down_cv_mn <- add_missing_names(df_down_cv,
                                   missing_cv_down,
                                   down_compare_cv@geneClusters
                                   )

# add states to split later
df_up_cv_mn$State <- df_up_cv_mn$Cluster
levels(df_up_cv_mn$State) <- rep(c("Crypts","Villi"), each = 3)

df_down_cv_mn$State <- df_down_cv_mn$Cluster
levels(df_down_cv_mn$State) <- rep(c("Crypts","Villi"), each = 3)

lvl.repl.down <- stri_replace_all_regex(levels(df_down_cv_mn$Cluster),
                                        pattern = c(".crypts",".villi"),
                                        replacement = "",
                                        vectorize_all = F)

lvl.repl.up <- stri_replace_all_regex(levels(df_up_cv_mn$Cluster),
                                        pattern = c(".crypts",".villi"),
                                        replacement = "",
                                        vectorize_all = F)

levels(df_up_cv_mn$Cluster) <- lvl.repl.up
levels(df_down_cv_mn$Cluster) <- lvl.repl.down
```

# Clustering
```{r}
clust_met <- "complete"

markers.down <- df_down_cv_mn$Description %>% unique()
markers.up <- df_up_cv_mn$Description %>% unique()

p.mat.down <- df_down_cv_mn %>% 
  filter(Description %in% markers.down) %>% 
  dplyr::select(Description,Cluster,p.adjust) %>%
  pivot_wider(names_from = Cluster,values_from = p.adjust) %>%
  data.frame() # make df

row.names(p.mat.down) <- p.mat.down$Description  # put Description in `row`
p.mat.down <- p.mat.down[,-1] #drop Description column as now in rows
p.mat.down[is.na(p.mat.down)] <- 0

# hclust with distance matrix
clust.down <- hclust(dist(p.mat.down %>% as.matrix()),method = clust_met) 

p.mat.up <- df_up_cv_mn %>% 
  filter(Description %in% markers.up) %>% 
  dplyr::select(Description,Cluster,p.adjust) %>%
  pivot_wider(names_from = Cluster,values_from = p.adjust) %>%
  data.frame() # make df

row.names(p.mat.up) <- p.mat.up$Description  # put Description in `row`
p.mat.up <- p.mat.up[,-1] #drop Description column as now in rows
p.mat.up[is.na(p.mat.up)] <- 0

# hclust with distance matrix
clust.up <- hclust(dist(p.mat.up %>% as.matrix()),method = clust_met) 
```

#Plotting
```{r}
theme.dp_cv <- list(
  # 1. Geoms
  geom_point(stroke = 0),
  
  # 2. Facets & scales
  theme_dose(7),
  facet_grid(~ State, scales = "free", space = "free", switch = "y"),
  scale_color_gradient(
    low = pos_color_low,
    high = pos_color_high,
    limits = c(0, max_p_cv) # adjust limits
  ),
  # scale_size_continuous(
  #   limits = c(min_gr_cv, max_gr_cv) # adjust limits
  # ),
  
  # 3. Labels & guides
  ylab(NULL),
  labs(color = "-log10 (p.adjust)"),
  guides(
    size = guide_legend(order = 2, stroke = 0),
    color = guide_colorbar(
      order = 1,
      title.theme = element_text(
        margin = margin(-15, 0, 0, 0, "pt")
      )
    )
  ),
  
  # 4. Theme adjustments
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
    axis.ticks = element_blank(),
    
    strip.background = element_blank(),
    strip.background.x = element_blank(),
    strip.background.y = element_blank(),
    strip.placement = "outside",
    strip.text = element_text(face = "bold", size = 7),
    
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 7),
    legend.title.position = "top",
    legend.position = "inside",
    legend.position.inside = c(2, -0.07), # GO
    legend.direction = "horizontal",
    legend.box = "vertical",
    legend.spacing.x = unit(0.025, "cm"),
    legend.key.spacing.x = unit(0.01, "cm"),
    legend.background = element_blank(),
    legend.box.background = element_blank(),
    
    panel.background = element_blank(),
    plot.background = element_blank()
  )
)


#add foldenrichment

df_up_cv_mn <- df_up_cv_mn %>% mutate(FoldEnrichment = (GeneRatio / parse_ratio(BgRatio)))

df_up_cv_mn_rc <- df_up_cv_mn

df_up_cv_mn_rc$Description <- fct_relevel(
  df_up_cv_mn_rc$Description,
  rev(clust.up$labels[clust.up$order]))

df_up_cv_mn_rc$Description_trunc <- sapply(df_up_cv_mn_rc$Description,
                                           truncate_go_term)

df_up_cv_mn_rc$ID_desc <- paste(df_up_cv_mn_rc$ID,
                                df_up_cv_mn_rc$Description_trunc)

df_up_cv_mn_rc <- df_up_cv_mn_rc %>%
  mutate(p.adjust = ifelse(p.adjust > max_p_cv, max_p_cv, p.adjust))

# GO and Pathway down 
df_down_cv_mn <- df_down_cv_mn %>% 
  mutate(FoldEnrichment = (GeneRatio / parse_ratio(BgRatio)))

df_down_cv_mn_rc <- df_down_cv_mn

df_down_cv_mn_rc$Description <- fct_relevel(
  df_down_cv_mn$Description,
  rev(clust.down$labels[clust.down$order]))

df_down_cv_mn_rc$Description_trunc <- sapply(df_down_cv_mn_rc$Description,
                                             truncate_go_term)

df_down_cv_mn_rc$ID_desc <- paste(df_down_cv_mn_rc$ID,
                                df_down_cv_mn_rc$Description_trunc)

df_down_cv_mn_rc <- df_down_cv_mn_rc %>%
  mutate(p.adjust = ifelse(p.adjust > max_p_cv, max_p_cv, p.adjust))
```


```{r}
dp_up_cv_mn_rc <- ggplot(df_up_cv_mn_rc, 
                         aes(x = Cluster, 
                             #y = reorder(ID_desc, p.adjust),
                             y = Description,
                             size = FoldEnrichment, color = p.adjust)) +
  theme.dp_cv + scale_y_discrete(position = "right") + 
  #ggtitle(glue("crypt/villus {NAME} up row cluster")) +
  #theme(legend.position =  c(1.7,-0.07)) # kegg
  theme(legend.position =  c(1.85,-0.08)) # reactome

dp_down_cv_mn_rc <- ggplot(df_down_cv_mn_rc,
                           aes(x = Cluster,
                               y = Description,
                               #y = reorder(ID_desc, p.adjust), 
                               size = FoldEnrichment, color = p.adjust)) +
  theme.dp_cv + scale_y_discrete(position = "right") +  
  scale_color_gradient(low = neg_color_low,
                       high = neg_color_high,
                       limits = c(0,max_p_cv)) 
  #ggtitle(glue("crypt/villus {NAME} down row cluster"))
```

#Saving
```{r}
save_ggplot_formats(
  plt = dp_up_cv_mn_rc,
  create_plot_subdir = TRUE,
  base_plot_dir = plots_folder,
  plt_name = glue("{NAME}_dotplot.up_cv_rc_FE"),
  width = 4.5,height = 4
  )

save_ggplot_formats(
  plt = dp_down_cv_mn_rc,
  create_plot_subdir = TRUE,
  base_plot_dir = plots_folder,
  plt_name = glue("{NAME}_dotplot.down_cv_rc_FE"),
  width = 3.5,height = 2.75
  )
```

```{r}
# write.csv(as.data.frame(df_down_cv_mn_rc),
#             file = file.path(charts_folder,
#                              glue("down_compare_filter_{NAME}.csv")),
#             row.names = FALSE)
# 
# write.csv(as.data.frame(df_up_cv_mn_rc),
#             file = file.path(charts_folder,
#                              glue("up_compare_filter_{NAME}.csv")),
#             row.names = FALSE)
```

