---
title: "GO_dotplot"
author: "Johannes Schöneich"
date: "`r Sys.Date()`"
output: html_document
---

# Load libraries
```{r}
library(clusterProfiler)
library(enrichplot)
library(DOSE)
library(tidyverse)
library(glue)
library(limma)
library(ReactomePA)
```

# Adjustments
```{r}
set.seed(1234)
harddrive  <- "H:"

analysis_folder <- file.path(harddrive,"DE_analysis/DE_Proteomics/")

source(file.path(harddrive,"DE_analysis/helper_functions.R"))

results.list <- readRDS(
  file.path(analysis_folder,"DE_results.list_proteomics.Rds")
  )

filter_names <- c("d01_d05","d05_d10","d10_d25")

results.list_filter <- results.list[filter_names]

plots_folder <- file.path(analysis_folder,"GO/plots")

charts_folder <- file.path(analysis_folder,"GO/charts/")

GO_save_folder <- file.path(analysis_folder,
                          "GO/saves/")

pathway_save_folder <- file.path(analysis_folder,
                          "Pathway/saves/")

# Which ontology: choose between all, biological process (bp), 
# molecular function (mf) and cellular component (cc).
ont <- "bp"

# P-adjust cutoff. Adjustment method is benjamini-hochberg (FDR)
p.cutoff <- 0.05

# The number of GO terms to compare
topN  <- 10

# Count cutoff. The low end filtering of counts
count.cutoff <- 10

# Heatmap coloring options
pos_color_low <- "#FFF5F0"
pos_color_high <- "#E41A1C" # The color to which the significant p-values converge

neg_color_low <- "#F7FBFF"
neg_color_high <- "#377EB8"

# One of GO, KEGG, Reactome or all
# if you choose all, you need to loop through them manually 
comparison <- "all"

#analysis name for plot names
NAME <- "ID_GO_truncated"
```

# Get significant genes
```{r}
add_missing_names <- function(df,missing_names,geneClusters, sort = TRUE){
  require(glue)
  # a function that takes a fortified data.frame as input, the missing names
  # from the analysis and the geneClusters from the GO output
  missing_length <- sapply(geneClusters[
    names(geneClusters) %in% missing_names],length)
  
  missing_names <- glue("{names(missing_length)} ({missing_length})")
  
  n_cols <- ncol(df)
  
  # Create a new data frame with the same number of columns as the df
  new_rows <- data.frame(matrix(NA, nrow = length(missing_names), 
                                ncol = n_cols))
  # Set the values from vector missing_names in the first column
  new_rows[, 1] <- missing_names 
  
  # Rename the columns of new_rows to match your original data frame
  colnames(new_rows) <- colnames(df)
  new_rows$Description <- df$Description[1:length(missing_names)]
  new_rows$ID <- df$ID[1:length(missing_names)]
  
  # Combine the new data frame with your existing data frame
  df_new <- rbind(df, new_rows)
  if(sort == TRUE){
    df_new$Cluster <- fct_relevel(df_new$Cluster,c(
      sort(grep("d01_d05",levels(df_new$Cluster),value = TRUE)),
      sort(grep("d05_d10",levels(df_new$Cluster),value = TRUE)),
      sort(grep("d10_d25",levels(df_new$Cluster),value = TRUE))
    ))
  }
  return(df_new)
}

# Function to truncate a GO term to the last space before maximum length
truncate_go_term <- function(term,max_length = 33) {
    term <- as.character(term)
    # Check if the term length is already within the limit
    if (nchar(term) <= max_length) {
      return(term)
    } else {
      # Find the last space before the maximum length
      last_space <- max(gregexpr("\\s", substr(term, 1, max_length))[[1]])
      truncated_term <- substr(term, 1, last_space - 1)
      return(paste0(truncated_term, "[...]"))
    }
  }

res_up <- lapply(results.list_filter,function(df){
  sigsdf_up <- df[(df$log2FoldChange >= 1) & (df$padj <= 0.05),]
  upgene <- (sigsdf_up$symbol)
  return(upgene)
})

res_down <- lapply(results.list_filter,function(df){
  sigsdf_down <- df[(df$log2FoldChange <= - 1) & (df$padj <= 0.05),]
  downgene <- (sigsdf_down$symbol)
  return(downgene)
})

up_entrez <- lapply(res_up,function(upgene){
  gene_e <- bitr(upgene, fromType="SYMBOL", toType = "ENTREZID", 
                    OrgDb =  "org.Mm.eg.db")
  return(gene_e[["ENTREZID"]])
})

down_entrez <- lapply(res_down,function(downgene){
  gene_e <- bitr(downgene, fromType = "SYMBOL", toType = "ENTREZID", 
                    OrgDb =  "org.Mm.eg.db")
  return(gene_e[["ENTREZID"]])
})
```

# Calculate GO/Pathways and compare cluster
```{r}
if(comparison == "GO"| comparison == "all"){
  up_compare_GO <- compareCluster(res_up,
                             fun = enrichGO,
                             OrgDb = "org.Mm.eg.db",
                             keyType = "SYMBOL",
                             ont = ont,
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(up_compare_GO),
            file = file.path(charts_folder,
                             "up_compare_proteomics_GO.csv"),
            row.names = FALSE)
  up_compare <- up_compare_GO
}

if(comparison == "Reactome"| comparison == "all"){
  up_compare_reactome <- compareCluster(up_entrez,
                             fun = enrichPathway,
                             organism = "mouse",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  write.csv(as.data.frame(up_compare_reactome),
            file = file.path(charts_folder,
                             "up_compare_proteomics_reactome.csv"),
            row.names = FALSE)
  up_compare <- up_compare_reactome
}

if(comparison == "KEGG"| comparison == "all"){
  up_compare_KEGG <- compareCluster(up_entrez,
                             fun = enrichKEGG,
                             organism = "mmu",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             )
  up_compare_KEGG <- setReadable(up_compare_KEGG,
                                 "org.Mm.eg.db",
                                 keyType = "ENTREZID")
  
  up_compare_KEGG@compareClusterResult$Description <- gsub(
      " - Mus musculus \\(house mouse)","",
      up_compare_KEGG@compareClusterResult$Description)
    
    write.csv(as.data.frame(up_compare_KEGG),
            file = file.path(charts_folder,
                             "up_compare_proteomics_Kegg.csv"),
            row.names = FALSE)
  up_compare <- up_compare_KEGG
}
```

```{r}
if(comparison == "GO"| comparison == "all"){
  down_compare_GO <- compareCluster(res_down,
                             fun = enrichGO,
                             OrgDb = "org.Mm.eg.db",
                             keyType = "SYMBOL",
                             ont = ont,
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  
  write.csv(as.data.frame(down_compare_GO),
            file = file.path(charts_folder,
                             "down_compare_proteomics_GO.csv"),
            row.names = FALSE)
  
  down_compare <- down_compare_GO
}

if(comparison == "Reactome"| comparison == "all"){
  down_compare_reactome <- compareCluster(down_entrez,
                             fun = enrichPathway,
                             organism = "mouse",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             readable = TRUE
                             )
  
  write.csv(as.data.frame(down_compare_reactome),
            file = file.path(charts_folder,
                             "down_compare_proteomics_reactome.csv"),
            row.names = FALSE)
  
  down_compare <- down_compare_reactome
}

if(comparison == "KEGG"| comparison == "all"){
  down_compare_KEGG <- compareCluster(down_entrez,
                             fun = enrichKEGG,
                             organism = "mmu",
                             pAdjustMethod = "BH",
                             pvalueCutoff  = p.cutoff,
                             )
  
  down_compare_KEGG <- setReadable(down_compare_KEGG,
                                   "org.Mm.eg.db",
                                   keyType = "ENTREZID")
  
  down_compare_KEGG@compareClusterResult$Description <- gsub(
    " - Mus musculus \\(house mouse)","",
  down_compare_KEGG@compareClusterResult$Description)
  
  write.csv(as.data.frame(down_compare_KEGG),
            file = file.path(charts_folder,
                             "down_compare_proteomics_Kegg.csv"),
            row.names = FALSE)
  
  down_compare <- down_compare_KEGG
}
```
# Save results
```{r}
dir.create(GO_save_folder)
dir.create(pathway_save_folder)

saveRDS(down_compare_GO,
        file.path(GO_save_folder,"down_compare_GO.Rds"))
saveRDS(down_compare_KEGG,
        file.path(pathway_save_folder,"down_compare_kegg.Rds"))
saveRDS(down_compare_reactome,
        file.path(pathway_save_folder,"down_compare_reactome.Rds"))

saveRDS(up_compare_GO,
        file.path(GO_save_folder,"up_compare_GO.Rds"))
saveRDS(up_compare_KEGG,
        file.path(pathway_save_folder,"up_compare_kegg.Rds"))
saveRDS(up_compare_reactome,
        file.path(pathway_save_folder,"up_compare_reactome.Rds"))
```

# Load previous results
```{r}
down_compare_GO <- readRDS(file.path(GO_save_folder,
                                     "down_compare_GO.Rds"))
down_compare_kegg <- readRDS(file.path(pathway_save_folder,
                                       "down_compare_kegg.Rds"))
down_compare_reactome <- readRDS(file.path(pathway_save_folder,
                                       "down_compare_reactome.Rds"))

up_compare_GO <- readRDS(file.path(GO_save_folder,
                                   "up_compare_GO.Rds"))
up_compare_kegg <- readRDS(file.path(pathway_save_folder,
                                       "up_compare_kegg.Rds"))
up_compare_reactome <- readRDS(file.path(pathway_save_folder,
                                       "up_compare_reactome.Rds"))
```

```{r}
# Dynamically adjust plot width based on topN or the number of clusters
adjust_plot_width <- function(topN) {
  # Starting width for plots
  base_width <- 10                          
  # Extra width based on top categories
  additional_width <- ceiling(topN / 5)     
  base_width + additional_width
}

# General plotting and saving function with dynamic plot size and format options
process_and_plot_GO <- function(
  up_compare,
  NAME,
  count.cutoff,
  topN,
  plots_folder,
  charts_folder,
  low_col,
  high_col,
  save_plot = TRUE,
  save_formats = c("csv", "xlsx")
) {

  filter_names <- c("d01_d05", "d05_d10", "d10_d25")
  
  # Filter and arrange by p-value
  up_compare_filter <- up_compare %>%
    filter(Count > count.cutoff) %>%
    arrange(p.adjust)
  
  # Transform adjusted p-value to -log10
  up_compare_filter@compareClusterResult$p.adjust <-
    -log10(up_compare_filter@compareClusterResult$p.adjust)
  
  # Set max p-value for color scale
  max_p <- min(max(up_compare_filter@compareClusterResult$p.adjust), 30)
  
  # Prepare data for plotting (topN categories)
  df_up <- fortify(
    up_compare_filter,
    showCategory = topN,
    split = NULL
    ) %>%
    droplevels() %>%
    mutate(Cluster = gsub("\n", " ", Cluster))
  
  missing_up <- filter_names[
    filter_names %ni% strsplit2(unique(df_up$Cluster), " ")[, 1]
  ]
  
  df_up <- add_missing_names(
    df_up,
    missing_up,
    up_compare@geneClusters,
    sort = TRUE
  )
  
  # Clustering
  p.mat.up <- df_up %>%
    dplyr::select(Description, Cluster, p.adjust) %>%
    pivot_wider(
      names_from = Cluster,
      values_from = p.adjust,
      values_fill = 0
    ) %>%
    column_to_rownames("Description") %>%
    as.matrix() %>%
    dist() %>%
    hclust(method = "complete")
  
  # Update factor levels based on clustering
  df_up_rc <- df_up %>%
    mutate(
      Description = fct_relevel(Description,
                                rev(p.mat.up$labels[p.mat.up$order])),
      Description_trunc = sapply(Description, 
                                 truncate_go_term, 
                                 max_length = 30),
      ID_desc = paste(ID, Description_trunc),
      p.adjust = pmin(p.adjust, max_p),
      FoldEnrichment = GeneRatio / parse_ratio(BgRatio)
    )
  
  # Plot Saving
  plot_width <- adjust_plot_width(topN)
  plot_height <- 8
  
  theme.dp <- list(
    geom_point(),
    theme_dose(5),
    coord_fixed(ratio = 1),
    scale_color_gradient(
      low = low_col,
      high = high_col
    ),
    scale_size_continuous(),
    ylab(NULL),
    theme(
      text = element_text(size = 7),
      axis.title = element_blank(),
      axis.text.x = element_text(
        angle = 90,
        hjust = 1,
        vjust = 0.5
      ),
      axis.ticks = element_blank(),
      legend.text = element_text(size = 7),
      legend.position = c(2, 0),
      legend.direction = "horizontal",
      legend.box = "vertical",
      legend.spacing.x = unit(0.05, 'cm')
    ),
    labs(color = "-log10 (p.adjust)"),
    guides(
      size = guide_legend(order = 2),
      color = guide_colorbar(order = 1)
    )
  )
  
  # Create dotplot with Fold Enrichment
  dp_up_FE <- ggplot(
    df_up_rc,
    aes(
      x = Cluster,
      y = ID_desc,
      size = FoldEnrichment,
      color = p.adjust
    )
  ) +
    theme.dp +
    scale_y_discrete(position = "right")
  
  if (save_plot) {
    save_ggplot_formats(
      plt = dp_up_FE,
      create_plot_subdir = TRUE,
      base_plot_dir = plots_folder,
      plt_name = glue("{NAME}_dotplot_up_rc_foldenrichment"),
      width = plot_width,
      height = plot_height
    )
  } else {
    return(dp_up_FE)
  }
  
  # Chart Saving
  if (length(save_formats) > 0) {
    
    # Prepare file paths
    csv_file_path <- append_timestamp(
      file.path(charts_folder, glue("up_compare_filter_{NAME}.csv"))
    )
    excel_file_path <- append_timestamp(
      file.path(charts_folder, glue("up_compare_filter_{NAME}.xlsx"))
    )
    
    # Save in specified formats
    if ("csv" %in% save_formats) {
      tryCatch(
        write.csv(as.data.frame(df_up_rc), 
                  file = csv_file_path,
                  row.names = FALSE),
        error = function(e) message(
          glue("Error saving CSV for {NAME}: {e$message}"))
      )
    }
    
    if ("xlsx" %in% save_formats) {
      tryCatch(
        write.xlsx(as.data.frame(df_up_rc),
                   file = excel_file_path, 
                   row.names = FALSE),
        error = function(e) message(
          glue("Error saving Excel for {NAME}: {e$message}"))
      )
    }
  }
}

```


```{r}
# Define datasets and corresponding names
datasets <- list(
  GO = unique_infected_compare_GO,
  KEGG = unique_infected_compare_KEGG,
  Reactome = unique_infected_compare_reactome
)

# Loop through datasets and process each
for (NAME in names(datasets)) {
  # Call the function with desired save options (set TRUE/FALSE as needed)
  process_and_plot_GO(
    datasets[[NAME]], 
    NAME, 
    count.cutoff = count.cutoff, 
    topN = topN, 
    plots_folder = plots_folder, 
    charts_folder = charts_folder, 
    save_plot = TRUE,         # Save the plot
    save_formats = c("csv", "xlsx")  # Save as both CSV and Excel
  )
}

```


```{r}
# Define datasets and corresponding names
datasets <- list(
  GO_UP = up_compare_GO,
  GO_DOWN = down_compare_GO
)

plot_list_go <- list()

plot_list_go[[1]] <- process_and_plot(
    datasets[[1]], 
    "GO_UP", 
    count.cutoff = count.cutoff, 
    topN = topN, 
    plots_folder = plots_folder, 
    charts_folder = charts_folder, 
    low_col = pos_color_low,
    high_col = pos_color_high,
    save_plot = FALSE,     # Save the plot
    save_formats = FALSE  # Save as both CSV and Excel
  )

plot_list_go[[2]] <- process_and_plot(
    datasets[[2]], 
    "GO_DOWN", 
    count.cutoff = count.cutoff, 
    topN = topN, 
    plots_folder = plots_folder, 
    charts_folder = charts_folder, 
    low_col = neg_color_low,
    high_col = neg_color_high,
    save_plot = FALSE,     # Save the plot
    save_formats = FALSE  # Save as both CSV and Excel
  )
```


```{r}
fig3_folder <- file.path(harddrive,"figures/figure_3/saves/")

saveRDS(plot_list_go,file.path(fig3_folder,"go_dotplot_fig3.Rds"))

save_ggplot_formats(
  plt = plot_list_go[[1]] ,
  create_plot_subdir = F,
  base_plot_dir = fig3_folder,
  plt_name = glue("fig3_GO_dotplot.up_rc"),
  width = 5,height = 8
  )

save_ggplot_formats(
  plt = plot_list_go[[2]] ,
  create_plot_subdir = F,
  base_plot_dir = fig3_folder,
  plt_name = glue("fig3_GO_dotplot.down_rc"),
  width = 5,height = 8
  )
```

# Calculations
```{r}
# if you choose all, you need to loop through them manually
up_compare <- up_compare_GO
down_compare <- down_compare_GO

# Filter and arrange by p-value
up_compare_filter <- filter(up_compare,
                            Count > count.cutoff) %>% arrange(p.adjust)

# -log of adjusted p.value
up_compare_filter@compareClusterResult$p.adjust <- 
  -log10(up_compare_filter@compareClusterResult$p.adjust)

# Filter and arrange by p.value
down_compare_filter <- filter(down_compare,#
                              Count > count.cutoff) %>% arrange(p.adjust)

# -log of p.value
down_compare_filter@compareClusterResult$p.adjust <- -log10(
  down_compare_filter@compareClusterResult$p.adjust )
```

# Maximal and minimal p-values for scales
```{r}
max_p <- max(down_compare_filter@compareClusterResult$p.adjust,
                     up_compare_filter@compareClusterResult$p.adjust)

if(max_p >30){max_p <- 30}
```

# Plotting
```{r}
# make data frames for plotting. Only use topN terms per Cluster
df_up <- fortify(up_compare_filter, 
                         showCategory = topN, split = NULL)
df_up <- droplevels(df_up)

df_down <- fortify(down_compare_filter, 
                           showCategory = topN, split = NULL)
df_down <- droplevels(df_down)

x_labels_up <- gsub("\n"," ",levels(df_up$Cluster))
x_labels_down <- gsub("\n"," ",levels(df_down$Cluster))

levels(df_up$Cluster) <- x_labels_up
levels(df_down$Cluster) <- x_labels_down

missing_up <- filter_names[filter_names %ni% 
                                  strsplit2(unique(df_up$Cluster)," ")[,1]]

missing_down <- filter_names[filter_names %ni% 
                                    strsplit2(unique(df_down$Cluster)," ")[,1]]

df_up <- add_missing_names(df_up,
                           missing_up,
                           up_compare@geneClusters,
                           sort = TRUE
                           )

df_down <- add_missing_names(df_down,
                             missing_down,
                             down_compare@geneClusters,
                             sort = TRUE
                             )
```

# Clustering
```{r}
clust_method <- "complete"

markers.down <- df_down$Description %>% unique()
markers.up <- df_up$Description %>% unique()

p.mat.down <- df_down %>% 
  filter(Description %in% markers.down) %>% 
  dplyr::select(Description,Cluster,p.adjust) %>%
  pivot_wider(names_from = Cluster,values_from = p.adjust) %>%
  data.frame() # make df
row.names(p.mat.down) <- p.mat.down$Description  # put gene in `row`
p.mat.down <- p.mat.down[,-1] #drop gene column as now in rows
p.mat.down[is.na(p.mat.down)] <- 0

# hclust with distance matrix
clust.down <- hclust(dist(p.mat.down %>% as.matrix()),method = clust_method) 

p.mat.up <- df_up %>% 
  filter(Description %in% markers.up) %>% 
  dplyr::select(Description,Cluster,p.adjust) %>%
  pivot_wider(names_from = Cluster,values_from = p.adjust) %>%
  data.frame() # make df as tibbles -> matrix annoying
row.names(p.mat.up) <- p.mat.up$Description  # put gene in `row`
p.mat.up <- p.mat.up[,-1] #drop gene column as now in rows
p.mat.up[is.na(p.mat.up)] <- 0

# hclust with distance matrix
clust.up <- hclust(dist(p.mat.up %>% as.matrix()),method = clust_method) 
```

# Plotting
```{r}
 theme.dp <- list(
  geom_point(),
  theme_dose(7),
  coord_fixed(ratio = 1),
  #adjust limits
  scale_color_gradient(low = low_col, high = high_col),
  scale_size_continuous(),  #adjust limits
  ylab(NULL),
  theme(text = element_text(size = 7),
    axis.title = element_blank(),
        axis.text.x = element_text(angle = 90,
                                   hjust = 1, 
                                   vjust = .5
                                   ),
        legend.text = element_text(size = 7),
    legend.position = c(2,-0.11), # GO
        #legend.position = c(3,-0.1), # kegg
        #legend.position = c(2.5,-0.1), # reactome
        legend.direction = "horizontal",
        legend.box = "vertical",
        legend.spacing.x = unit(0.05, 'cm')
  ),
  labs(color = "-log10 (p.adjust)"),
  guides(size = guide_legend(order = 2),
         color = guide_colorbar(order = 1)
         )
  )


# GO + Pathway Up
df_up_rc <- df_up

df_up_rc$Description <- fct_relevel(df_up_rc$Description,
                                rev(clust.up$labels[clust.up$order]))

df_up_rc$Description_trunc <- sapply(df_up_rc$Description, truncate_go_term)

df_up_rc$ID_desc <- paste(df_up_rc$ID,df_up_rc$Description_trunc)

df_up_rc <- df_up_rc %>%
  mutate(p.adjust = ifelse(p.adjust > max_p, max_p, p.adjust))

# GO + Pathway Down
df_down_rc <- df_down

df_down_rc$Description <- fct_relevel(df_down$Description,
                                rev(clust.down$labels[clust.down$order]))

df_down_rc$Description_trunc <- sapply(df_down_rc$Description,
                                       truncate_go_term)

df_down_rc$ID_desc <- paste(df_down_rc$ID,df_down_rc$Description_trunc)

df_down_rc <- df_down_rc %>%
  mutate(p.adjust = ifelse(p.adjust > max_p, max_p, p.adjust))

dp_up_rc <- ggplot(df_up_rc, aes(x = Cluster, y = ID_desc, 
                               size = GeneRatio, color = p.adjust)) +
  theme.dp + scale_y_discrete(position = "right") +
  ggtitle(glue("{NAME} up row cluster"))

dp_down_rc <- ggplot(df_down_rc, aes(x = Cluster, y = ID_desc, 
                                     size = GeneRatio, color = p.adjust)) +
  theme.dp + scale_y_discrete(position = "right") +
  scale_color_gradient(low = neg_color_low,
                       high = neg_color_high,
                       limits = c(0,max_p)) + theme(legend.position = c(2.63,-0.1)) +
  ggtitle(glue("{NAME} down row cluster"))
```

# Saving

## Save Plots
```{r}
save_ggplot_formats(
  plt = dp_up_rc,
  create_plot_subdir = T,
  base_plot_dir = plots_folder,
  plt_name = glue("{NAME}_dotplot.up_rc"),
  width = 5,height = 8
  )

save_ggplot_formats(
  plt = dp_down_rc,
  create_plot_subdir = T,
  base_plot_dir = plots_folder,
  plt_name = glue("{NAME}_dotplot.down_rc"),
  width = 5,height = 8
  )
```
## Save Tables
```{r}
write.csv(as.data.frame(df_down_rc),
            file = file.path(charts_folder,
                             glue("down_compare_filter_{NAME}.csv")),
            row.names = FALSE)

write.csv(as.data.frame(df_up_rc),
            file = file.path(charts_folder,
                             glue("up_compare_filter_{NAME}.csv")),
            row.names = FALSE)
```

